=== LorincAkos/XVG56EWebXML/XVG56E_1015/XVG56E_XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Egyszerű típusok-->
    <xs:element name="vendeglatas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="etterem" type="etteremTipus" maxOccurs="unbounded"></xs:element>
                <xs:element name="foszakacs" type="foszakacsTipus" maxOccurs="unbounded"></xs:element>
                <xs:element name="szakacs" type="szakacsTipus" maxOccurs="unbounded"></xs:element>
                <xs:element name="gyakornok" type="gyakornokTipus" maxOccurs="unbounded"></xs:element>
                <xs:element name="vendeg" type="vendegTipus" maxOccurs="unbounded"></xs:element>
                <xs:element name="rendeles" type="rendelesTipus" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>

        <!-- Kulcsok-->
         <xs:key name="etterem_kulcs">
            <xs:selector xpath="etterem"></xs:selector>
            <xs:field xpath="@ekod"></xs:field>
         </xs:key>

         <xs:key name="foszakacs_kulcs">
            <xs:selector xpath="foszakacs"></xs:selector>
            <xs:field xpath="@fkod"></xs:field>
         </xs:key>

         <xs:key name="szakacs_kulcs">
            <xs:selector xpath="szakacs"></xs:selector>
            <xs:field xpath="@szkod"></xs:field>
         </xs:key>
        
         <xs:key name="gyakornok_kulcs">
            <xs:selector xpath="gyakornok"></xs:selector>
            <xs:field xpath="@gykod"></xs:field>
         </xs:key>
         
         <xs:key name="vendeg_kulcs">
            <xs:selector xpath="vendeg"></xs:selector>
            <xs:field xpath="@vkod"></xs:field>
         </xs:key>

         <!-- IDegen kulcsok-->

         <xs:keyref refer="etterem_kulcs" name="etterem_idegen_kulcs">
            <xs:selector xpath="rendeles"></xs:selector>
            <xs:field xpath="@e_v_e"></xs:field>
         </xs:keyref>
         
         <xs:keyref refer="vendeg_kulcs" name="vendeg_idegen_kulcs">
            <xs:selector xpath="rendeles"></xs:selector>
            <xs:field xpath="@e_v_v"></xs:field>
         </xs:keyref>

         
         <xs:keyref refer="etterem_kulcs" name="etterem_foszakacs_idegen_kulcs">
            <xs:selector xpath="foszakacs"></xs:selector>
            <xs:field xpath="@e_f"></xs:field>
         </xs:keyref>

         
         <xs:keyref refer="etterem_kulcs" name="etterem_szakacs_idegen_kulcs">
            <xs:selector xpath="szakacs"></xs:selector>
            <xs:field xpath="@e_sz"></xs:field>
         </xs:keyref>

         
         <xs:keyref refer="etterem_kulcs" name="etterem_gyakornok_idegen_kulcs">
            <xs:selector xpath="gyakornok"></xs:selector>
            <xs:field xpath="@e_gy"></xs:field>
         </xs:keyref>

         <!-- Az 1:1 kapcsolat megvalósításához-->

         <xs:unique name="unique_foszakacs">
         <xs:selector xpath="foszakacs"></xs:selector>
         <xs:field xpath="@e_f"></xs:field>
         </xs:unique>
    </xs:element>

    <!-- Komplex típusok-->
     <xs:complexType name="etteremTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"></xs:element>
            <xs:element name="cim" type="cimTipus"></xs:element>
            <xs:element name="csillag" type="xs:integer"></xs:element>
        </xs:sequence>
        <xs:attribute name="ekod" type="xs:string" use="required"></xs:attribute>
     </xs:complexType>

     <xs:complexType name="cimTipus">
        <xs:sequence>
            <xs:element name="varos" type="xs:string"></xs:element>
            <xs:element name="utca" type="xs:string"></xs:element>
            <xs:element name="hazszam" type="xs:integer"></xs:element>
        </xs:sequence>
     </xs:complexType>

     <xs:complexType name="foszakacsTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"></xs:element>
            <xs:element name="eletkor" type="xs:integer"></xs:element>
            <xs:element name="vegzetseg" type="xs:string" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
        <xs:attribute name="fkod" type="xs:string" use="required"></xs:attribute>
        <xs:attribute name="e_f" type="xs:string" use="required"></xs:attribute>
     </xs:complexType>

     <xs:complexType name="szakacsTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"></xs:element>
            <xs:element name="reszleg" type="xs:string" maxOccurs="unbounded"></xs:element>
            <xs:element name="vegzetseg" type="xs:string" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
        <xs:attribute name="szkod" type="xs:string" use="required"></xs:attribute>
        <xs:attribute name="e_sz" type="xs:string" use="required"></xs:attribute>
     </xs:complexType>

     
     <xs:complexType name="gyakornokTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"></xs:element>
            <xs:element name="gyakorlat" type="gyakorlatTipus"></xs:element>
            <xs:element name="muszak" type="xs:string" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
        <xs:attribute name="gykod" type="xs:string" use="required"></xs:attribute>
        <xs:attribute name="e_gy" type="xs:string" use="required"></xs:attribute>
     </xs:complexType>

     <xs:complexType name="gyakorlatTipus">
        <xs:sequence>
            <xs:element name="kezdete" type="xs:string"></xs:element>
            <xs:element name="idotartama" type="xs:string"></xs:element>
        </xs:sequence>
     </xs:complexType>

     
     <xs:complexType name="vendegTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"></xs:element>
            <xs:element name="eletkor" type="xs:integer"></xs:element>
            <xs:element name="cim" type="cimTipus"></xs:element>
        </xs:sequence>
        <xs:attribute name="vkod" type="xs:string" use="required"></xs:attribute>
     </xs:complexType>

     
     <xs:complexType name="rendelesTipus">
        <xs:sequence>
            <xs:element name="osszeg" type="xs:integer"></xs:element>
            <xs:element name="etel" type="xs:string" ></xs:element>
        </xs:sequence>
        <xs:attribute name="e_v_e" type="xs:string" use="required"></xs:attribute>
        <xs:attribute name="e_v_v" type="xs:string" use="required"></xs:attribute>
     </xs:complexType>
</xs:schema>

=== LorincAkos/XVG56EWebXML/XVG56E_1015/XVG56E_XML.xml
<?xml version="1.0" encoding="UTF-8"?>

<vendeglatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XVG56E_XMLSchema.xsd">

    <!-- Étterem-->
    <etterem ekod="e1">
        <nev>Trófea</nev>
        <cim>
            <varos>Budapest</varos>
            <utca>Visegrádi</utca>
            <hazszam>13</hazszam>
        </cim>
        <csillag>4</csillag>
    </etterem>

    <etterem ekod="e2">
        <nev>Gundel</nev>
        <cim>
            <varos>Budapest</varos>
            <utca>Gundel Károly</utca>
            <hazszam>4</hazszam>
        </cim>
        <csillag>5</csillag>
    </etterem>

    <!-- Főszakács-->
    <foszakacs fkod="f1" e_f="e1">
        <nev>Havas Péter</nev>
        <eletkor>35</eletkor>
        <vegzetseg>Szakközépiskola</vegzetseg>
        <vegzetseg>Instuit Paul Bocuse</vegzetseg>
    </foszakacs>

    <foszakacs fkod="f2" e_f="e2">
        <nev>Nagy Károly</nev>
        <eletkor>30</eletkor>
        <vegzetseg>Le Cordon Bleu</vegzetseg>
    </foszakacs>

    <!-- Szakács-->
    <szakacs szkod="sz1" e_sz="e1">
        <nev>Ötlet Elek</nev>
        <reszleg>Saucier</reszleg>
        <vegzetseg>Szakközépiskola</vegzetseg>
        <vegzetseg>Le Cordon Bleu</vegzetseg>
        <vegzetseg>Instuit Paul Bocuse</vegzetseg>
    </szakacs>

    <szakacs szkod="sz2" e_sz="e2">
        <nev>Kocsis Tibor</nev>
        <reszleg>Entrematier</reszleg>
        <vegzetseg>Szakközépiskola</vegzetseg>
        <vegzetseg>Le Cordon Bleu</vegzetseg>
    </szakacs>

    <szakacs szkod="sz3" e_sz="e2">
        <nev>Tálas Levente</nev>
        <reszleg>Gardemanger</reszleg>
        <vegzetseg>Szakközépiskola</vegzetseg>
    </szakacs>

    
    <szakacs szkod="sz4" e_sz="e1">
        <nev>Szűcs Judit</nev>
        <reszleg>Entrematier</reszleg>
        <vegzetseg>Le Cordon Bleu</vegzetseg>
        <vegzetseg>Instuit Paul Bocuse</vegzetseg>
    </szakacs>

    <!-- Gyakornok-->
        <gyakornok gykod="gy1" e_gy="e1">
            <nev>Bordás Dávid</nev>
            <gyakorlat>
                <kezdete>2021.08.20</kezdete>
                <idotartama>2 hónap</idotartama>
            </gyakorlat>
            <muszak>Délelőtt</muszak>
            <muszak>Este</muszak>
        </gyakornok>
        
        <gyakornok gykod="gy2" e_gy="e2">
            <nev>Szilágyi István</nev>
            <gyakorlat>
                <kezdete>2021.06.01</kezdete>
                <idotartama>4 hónap</idotartama>
            </gyakorlat>
            <muszak>Délután</muszak>
        </gyakornok>

        <gyakornok gykod="gy3" e_gy="e1">
            <nev>Szentpétery Ferenc</nev>
            <gyakorlat>
                <kezdete>2021.07.15</kezdete>
                <idotartama>3 hónap</idotartama>
            </gyakorlat>
            <muszak>Este</muszak>
        </gyakornok>

    <!-- Vendég-->
     <vendeg vkod="v1">
        <nev>Fekete Péter</nev>
        <eletkor>21</eletkor>
        <cim>
            <varos>Miskolc</varos>
            <utca>Márton</utca>
            <hazszam>17</hazszam>
        </cim>
     </vendeg>

     <vendeg vkod="v2">
        <nev>Bordás Áron</nev>
        <eletkor>25</eletkor>
        <cim>
            <varos>Eger</varos>
            <utca>Dobó</utca>
            <hazszam>12</hazszam>
        </cim>
     </vendeg>

     <!-- Rendelés-->

     <rendeles e_v_e="e1" e_v_v="v1">
        <osszeg>8000</osszeg>
        <etel>Kaviár</etel>
     </rendeles>

     <rendeles e_v_e="e2" e_v_v="v2">
        <osszeg>20000</osszeg>
        <etel>Zsíros kenyér</etel>
     </rendeles>
     
     <rendeles e_v_e="e1" e_v_v="v2">
        <osszeg>300</osszeg>
        <etel>Mackó sajt</etel>
     </rendeles>
     
     <rendeles e_v_e="e2" e_v_v="v1">
        <osszeg>9000</osszeg>
        <etel>Steak</etel>
     </rendeles>
</vendeglatas>
