=== LorincAkos/XVG56EWebXML/XVG56E_1008/XVG56E_orarend.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="unqualified"
           attributeFormDefault="unqualified">

  <xs:simpleType name="oraTipusTipus">
    <xs:restriction base="xs:string">
      <xs:enumeration value="eloadas"/>
      <xs:enumeration value="gyakorlat"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="oraIdType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="napType">
    <xs:restriction base="xs:string">
      <xs:pattern value="(paratlan )?(hetfo|kedd|szerda|csutortok|pentek)"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="idoType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{1,2}_\d{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="szakType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="mernokinformatika"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="idopontType">
    <xs:sequence>
      <xs:element name="nap" type="napType"/>
      <xs:element name="tol" type="idoType"/>
      <xs:element name="ig"  type="idoType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="oraType">
    <xs:sequence>
      <xs:element name="targy" type="xs:string"/>
      <xs:element name="idopont" type="idopontType"/>
      <xs:element name="helyszin" type="xs:string"/>
      <xs:element name="oktato" type="xs:string"/>
      <xs:element name="szak" type="szakType"/>
    </xs:sequence>
    <xs:attribute name="id" type="oraIdType" use="required"/>
    <xs:attribute name="tipus" type="oraTipusTipus" use="required"/>
  </xs:complexType>

  <xs:element name="xvg56e_orarend">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ora" type="oraType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>

    <xs:unique name="unique_ora_id">
      <xs:selector xpath="ora"/>
      <xs:field xpath="@id"/>
    </xs:unique>
  </xs:element>

</xs:schema>

=== LorincAkos/XVG56EWebXML/XVG56E_1008/XVG56E_orarend.xml
<?xml version="1.0" encoding="UTF-8"?>

<xvg56e_orarend 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="XVG56E_orarend.xsd">
    <ora id="01" tipus="eloadas">
        <targy>Elektrotechnika-elektronika</targy>
        <idopont>
            <nap>hetfo</nap>
            <tol>8_00</tol>
            <ig>10_00</ig>
        </idopont>
        <helyszin>III.ea</helyszin>
        <oktato>Szabó Norbert István</oktato>
        <szak>mernokinformatika</szak>
    </ora>

    <ora id="02" tipus="gyakorlat">
        <targy>Korszeru informacios technologiak</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>8_00</tol>
            <ig>10_00</ig>
        </idopont>
        <helyszin>In/103</helyszin>
        <oktato>Soós Róbert</oktato>
        <szak>mernokinformatika</szak>
    </ora>

    <ora id="03" tipus="eloadas">
        <targy>Korszeru informacios technologiak</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>10_00</tol>
            <ig>12_00</ig>
        </idopont>
        <helyszin>In/101</helyszin>
        <oktato>Árvai László Lajos</oktato>
        <szak>mernokinformatika</szak>
    </ora>

    
    <ora id="04" tipus="gyakorlat">
        <targy>Elektrotechnika-elektronika</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>12_00</tol>
            <ig>14_00</ig>
        </idopont>
        <helyszin>A1/317</helyszin>
        <oktato>Szabó Norbert István</oktato>
        <szak>mernokinformatika</szak>
    </ora>

    <ora id="05" tipus="eloadas">
        <targy>Web-es alkamazasok (Java)</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>16_00</tol>
            <ig>18_00</ig>
        </idopont>
        <helyszin>online</helyszin>
        <oktato>Dr. Barabas Peter</oktato>
        <szak>mernokinformatika</szak>
    </ora>

    <ora id="06" tipus="gyakorlat">
        <targy>Web-es alkamazasok (Java)</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>18_00</tol>
            <ig>20_00</ig>
        </idopont>
        <helyszin>online</helyszin>
        <oktato>Dr. Barabas Peter</oktato>
        <szak>mernokinformatika</szak>
    </ora>

    
    <ora id="07" tipus="eloadas">
        <targy>Webes adatkezelo kornyezetek</targy>
        <idopont>
            <nap>szerda</nap>
            <tol>8_00</tol>
            <ig>10_00</ig>
        </idopont>
        <helyszin>A1/310</helyszin>
        <oktato>Dr. Kovacs Laszlo Jozsef</oktato>
        <szak>mernokinformatika</szak>
    </ora>
    
    <ora id="08" tipus="gyakorlat">
        <targy>Webes adatkezelo kornyezetek</targy>
        <idopont>
            <nap>szerda</nap>
            <tol>10_00</tol>
            <ig>12_00</ig>
        </idopont>
        <helyszin>In/103</helyszin>
        <oktato>Dr. Bednarik Laszlo</oktato>
        <szak>mernokinformatika</szak>
    </ora>

    
    <ora id="09" tipus="gyakorlat">
        <targy>Szoftverteszteles</targy>
        <idopont>
            <nap>paratlan csutortok</nap>
            <tol>10_00</tol>
            <ig>14_00</ig>
        </idopont>
        <helyszin>In/103</helyszin>
        <oktato>Dr. Hornyak Olliver</oktato>
        <szak>mernokinformatika</szak>
    </ora>
</xvg56e_orarend>
