=== LorincAkos/XVG56EWebXML/XVG56E_XMLTask/XVG56EDOMParse/XVG56E_XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Egyszerű Típusok -->
    <xs:element name="myList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="felhasznalo" type="felhasznaloTipus" maxOccurs="unbounded"/>
                <xs:element name="osszefoglalo" type="osszefoglaloTipus" maxOccurs="unbounded"/>
                <xs:element name="studio" type="studioTipus" maxOccurs="unbounded"/>
                <xs:element name="anime" type="animeTipus" maxOccurs="unbounded"/>
                <xs:element name="karakter" type="karakterTipus" maxOccurs="unbounded"/>
                <xs:element name="megjelenes" type="megjelenesTipus" maxOccurs="unbounded"/>
                <xs:element name="mufaj" type="mufajTipus" maxOccurs="unbounded"/>
                <xs:element name="animemufaj" type="animeMufajTipus" maxOccurs="unbounded"/>
                <xs:element name="sajatlista" type="sajatListaTipus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <!-- Kulcsok -->
        <xs:key name="felhasznalo_kulcs">
            <xs:selector xpath="felhasznalo"/>
            <xs:field xpath="@fkod"/>
        </xs:key>

        <xs:key name="osszefoglalo_kulcs">
            <xs:selector xpath="osszefoglalo"/>
            <xs:field xpath="@okod"/>
        </xs:key>

        <xs:key name="studio_kulcs">
            <xs:selector xpath="studio"/>
            <xs:field xpath="@skod"/>
        </xs:key>

        <xs:key name="anime_kulcs">
            <xs:selector xpath="anime"/>
            <xs:field xpath="@akod"/>
        </xs:key>

        <xs:key name="karakter_kulcs">
            <xs:selector xpath="karakter"/>
            <xs:field xpath="@kkod"/>
        </xs:key>

        <xs:key name="mufaj_kulcs">
            <xs:selector xpath="mufaj"/>
            <xs:field xpath="@mkod"/>
        </xs:key>

        <!-- Idegen kulcsok -->
        <xs:keyref refer="felhasznalo_kulcs" name="felhasznalo_osszefoglalo_idegen_kulcs">
            <xs:selector xpath="osszefoglalo"/>
            <xs:field xpath="@o_f"/>
        </xs:keyref>

        <xs:keyref refer="studio_kulcs" name="studio_anime_idegen_kulcs">
            <xs:selector xpath="anime"/>
            <xs:field xpath="@a_s"/>
        </xs:keyref>

        <xs:keyref refer="anime_kulcs" name="anime_megjelenes_idegen_kulcs">
            <xs:selector xpath="megjelenes"/>
            <xs:field xpath="@a_k_a"/>
        </xs:keyref>

        <xs:keyref refer="karakter_kulcs" name="karakter_megjelenes_idegen_kulcs">
            <xs:selector xpath="megjelenes"/>
            <xs:field xpath="@a_k_k"/>
        </xs:keyref>

        <xs:keyref refer="anime_kulcs" name="anime_animemufaj_idegen_kulcs">
            <xs:selector xpath="animemufaj"/>
            <xs:field xpath="@a_m_a"/>
        </xs:keyref>

        <xs:keyref refer="mufaj_kulcs" name="mufaj_animemufaj_idegen_kulcs">
            <xs:selector xpath="animemufaj"/>
            <xs:field xpath="@a_m_m"/>
        </xs:keyref>

        <xs:keyref refer="felhasznalo_kulcs" name="felhasznalo_sajatlista_idegen_kulcs">
            <xs:selector xpath="sajatlista"/>
            <xs:field xpath="@f_a_f"/>
        </xs:keyref>

        <xs:keyref refer="anime_kulcs" name="anime_sajatlista_idegen_kulcs">
            <xs:selector xpath="sajatlista"/>
            <xs:field xpath="@f_a_a"/>
        </xs:keyref>

        <!-- Az 1:1 kapcsolat megvalósításához-->

        <xs:unique name="unique_osszefoglalo">
            <xs:selector xpath="osszefoglalo"></xs:selector>
            <xs:field xpath="@o_f"></xs:field>
        </xs:unique>
    </xs:element>

    <!-- Komplex Típusok-->
    <xs:complexType name="felhasznaloTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="regisztracio" type="xs:string"/>
            <xs:element name="kedvencmufaj" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="fkod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="osszefoglaloTipus">
        <xs:sequence>
            <xs:element name="totalanime" type="xs:int"/>
            <xs:element name="atlagpont" type="xs:int"/>
            <xs:element name="utolsofrissites" type="xs:string"/>
            <xs:element name="totalido" type="xs:int"/>
        </xs:sequence>
        <xs:attribute name="okod" type="xs:string" use="required"/>
        <xs:attribute name="o_f" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="studioTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="orszag" type="xs:string"/>
            <xs:element name="alapitas" type="xs:string"/>
            <xs:element name="projektek" type="xs:int"/>
        </xs:sequence>
        <xs:attribute name="skod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="animeTipus">
        <xs:sequence>
            <xs:element name="cim" type="xs:string"/>
            <xs:element name="tipus" type="xs:string"/>
            <xs:element name="kezdes" type="xs:string"/>
            <xs:element name="befejezes" type="xs:string"/>
            <xs:element name="epizod" type="xs:int"/>
        </xs:sequence>
        <xs:attribute name="akod" type="xs:string" use="required"/>
        <xs:attribute name="a_s" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="karakterTipus">
        <xs:sequence>
            <xs:element name="nev" type="karakterNevTipus"/>
            <xs:element name="kor" type="xs:int"/>
            <xs:element name="nem" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="kkod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="karakterNevTipus">
        <xs:sequence>
            <xs:element name="csaladnev" type="xs:string"/>
            <xs:element name="keresztnev" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="megjelenesTipus">
        <xs:sequence>
            <xs:element name="szerep" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="a_k_a" type="xs:string" use="required"/>
        <xs:attribute name="a_k_k" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="mufajTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="leiras" type="xs:string"/>
            <xs:element name="felnott" type="xs:boolean"/>
            <xs:element name="nepszerusegrang" type="xs:int"/>
        </xs:sequence>
        <xs:attribute name="mkod" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="animeMufajTipus">
        <xs:sequence>
            <xs:element name="elsodleges" type="xs:boolean"/>
        </xs:sequence>
        <xs:attribute name="a_m_a" type="xs:string" use="required"/>
        <xs:attribute name="a_m_m" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="sajatListaTipus">
        <xs:sequence>
            <xs:element name="statusz" type="xs:string"/>
            <xs:element name="pontszam" type="xs:int"/>
        </xs:sequence>
        <xs:attribute name="f_a_a" type="xs:string" use="required"/>
        <xs:attribute name="f_a_f" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>

=== LorincAkos/XVG56EWebXML/XVG56E_XMLTask/XVG56EDOMParse/XVG56E_XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<myList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="XVG56E_XMLSchema.xsd">

    <!-- Felhasználók -->
    <felhasznalo fkod='f1'>
        <nev>LAkos</nev>
        <email>LAkos@email.com</email>
        <regisztracio>2017.06.17</regisztracio>
        <kedvencmufaj>Akció</kedvencmufaj>
        <kedvencmufaj>Fantasy</kedvencmufaj>
        <kedvencmufaj>Horror</kedvencmufaj>
    </felhasznalo>

    <felhasznalo fkod='f2'>
        <nev>Lali01</nev>
        <email>Lali01@email.com</email>
        <regisztracio>2020.04.03</regisztracio>
        <kedvencmufaj>Komédia</kedvencmufaj>
    </felhasznalo>

    <felhasznalo fkod='f3'>
        <nev>User2</nev>
        <email>User2@email.com</email>
        <regisztracio>2022.01.29</regisztracio>
        <kedvencmufaj>Fantasy</kedvencmufaj>
        <kedvencmufaj>Komédia</kedvencmufaj>
    </felhasznalo>

    <!-- Felhasználó összefoglaló  -->
    <osszefoglalo okod='o1' o_f='f1'>
        <totalanime>154</totalanime>
        <atlagpont>8</atlagpont>
        <utolsofrissites>2025.08.14</utolsofrissites>
        <totalido>740</totalido>
    </osszefoglalo>

    <osszefoglalo okod='o2' o_f='f2'>
        <totalanime>76</totalanime>
        <atlagpont>7</atlagpont>
        <utolsofrissites>2025.03.19</utolsofrissites>
        <totalido>365</totalido>
    </osszefoglalo>

    <osszefoglalo okod='o3' o_f='f3'>
        <totalanime>32</totalanime>
        <atlagpont>9</atlagpont>
        <utolsofrissites>2024.12.28</utolsofrissites>
        <totalido>152</totalido>
    </osszefoglalo>

    <!-- Studió-->
    <studio skod='s1'>
        <nev>Madhouse</nev>
        <orszag>Japán</orszag>
        <alapitas>1972.10.17</alapitas>
        <projektek>397</projektek>
    </studio>

    <studio skod='s2'>
        <nev>Mappa</nev>
        <orszag>Japán</orszag>
        <alapitas>2011.06.14</alapitas>
        <projektek>110</projektek>
    </studio>

    <studio skod='s3'>
        <nev>A-1 Pictures</nev>
        <orszag>Japán</orszag>
        <alapitas>2005.05.09</alapitas>
        <projektek>216</projektek>
    </studio>

    <!-- Anime -->
    <anime akod='a1' a_s='s1'>
        <cim>Attack on Titan</cim>
        <tipus>TV</tipus>
        <kezdes>2013.04.07</kezdes>
        <befejezes>2013.09.29</befejezes>
        <epizod>24</epizod>
    </anime>
    <anime akod='a2' a_s='s2'>
        <cim>Tokyo Ghoul</cim>
        <tipus>OVA</tipus>
        <kezdes>2014.07.04</kezdes>
        <befejezes>2014.09.19</befejezes>
        <epizod>12</epizod>
    </anime>
    <anime akod='a3' a_s='s2'>
        <cim>KonoSuba</cim>
        <tipus>Film</tipus>
        <kezdes>2019.08.30</kezdes>
        <befejezes>2019.08.30</befejezes>
        <epizod>1</epizod>
    </anime>

    <!-- Karakter -->
    <karakter kkod='k1'>
        <nev>
            <csaladnev>Jager</csaladnev>
            <keresztnev>Eren</keresztnev>
        </nev>
        <kor>18</kor>
        <nem>Férfi</nem>
    </karakter>
    <karakter kkod='k2'>
        <nev>
            <csaladnev>Ackerman</csaladnev>
            <keresztnev>Mikasa</keresztnev>
        </nev>
        <kor>17</kor>
        <nem>Nő</nem>
    </karakter>
    <karakter kkod='k3'>
        <nev>
            <csaladnev>Kaneki</csaladnev>
            <keresztnev>Ken</keresztnev>
        </nev>
        <kor>20</kor>
        <nem>Férfi</nem>
    </karakter>
    <karakter kkod='k4'>
        <nev>
            <csaladnev>Kirisima</csaladnev>
            <keresztnev>Touka</keresztnev>
        </nev>
        <kor>19</kor>
        <nem>Nő</nem>
    </karakter>
    <karakter kkod='k5'>
        <nev>
            <csaladnev>Satou</csaladnev>
            <keresztnev>Kazuma</keresztnev>
        </nev>
        <kor>17</kor>
        <nem>Férfi</nem>
    </karakter>

    <!-- Megjelenés -->
    <megjelenes a_k_a='a1' a_k_k='k1'>
        <szerep>Főszerep</szerep>
    </megjelenes>

    <megjelenes a_k_a='a1' a_k_k='k2'>
        <szerep>Mellékszerep</szerep>
    </megjelenes>

    <megjelenes a_k_a='a2' a_k_k='k3'>
        <szerep>Főszerep</szerep>
    </megjelenes>

    <megjelenes a_k_a='a2' a_k_k='k4'>
        <szerep>Mellékszerep</szerep>
    </megjelenes>

    <megjelenes a_k_a='a3' a_k_k='k5'>
        <szerep>Főszerep</szerep>
    </megjelenes>

    <!-- Műfaj-->
    <mufaj mkod='m1'>
        <nev>Akció</nev>
        <leiras>Gyors tempójú, látványos harcjelenetekkel és intenzív konfliktusokkal teli műfaj.</leiras>
        <felnott>false</felnott>
        <nepszerusegrang>2</nepszerusegrang>
    </mufaj>
    <mufaj mkod='m2'>
        <nev>Fantasy</nev>
        <leiras>Mágikus világokkal, természetfeletti lényekkel és hősi kalandokkal foglalkozó műfaj.</leiras>
        <felnott>false</felnott>
        <nepszerusegrang>1</nepszerusegrang>
    </mufaj>
    <mufaj mkod='m3'>
        <nev>Horror</nev>
        <leiras>Feszült, félelmet keltő történeteket bemutató műfaj, gyakran erős ijesztő elemekkel.</leiras>
        <felnott>true</felnott>
        <nepszerusegrang>4</nepszerusegrang>
    </mufaj>
    <mufaj mkod='m4'>
        <nev>Komédia</nev>
        <leiras>Könnyed, humoros jelenetekkel és szórakoztató helyzetekkel operáló műfaj.</leiras>
        <felnott>false</felnott>
        <nepszerusegrang>3</nepszerusegrang>
    </mufaj>

    <!-- AnimeMűfaj -->
    <animemufaj a_m_a='a1' a_m_m='m1'>
        <elsodleges>true</elsodleges>
    </animemufaj>

    <animemufaj a_m_a='a1' a_m_m='m2'>
        <elsodleges>false</elsodleges>
    </animemufaj>

    <animemufaj a_m_a='a2' a_m_m='m3'>
        <elsodleges>true</elsodleges>
    </animemufaj>

    <animemufaj a_m_a='a2' a_m_m='m2'>
        <elsodleges>false</elsodleges>
    </animemufaj>

    <animemufaj a_m_a='a3' a_m_m='m2'>
        <elsodleges>true</elsodleges>
    </animemufaj>

    <animemufaj a_m_a='a3' a_m_m='m4'>
        <elsodleges>false</elsodleges>
    </animemufaj>

    <!-- SajátLista -->
    <sajatlista f_a_a='a1' f_a_f='f1'>
        <statusz>Befejezett</statusz>
        <pontszam>8</pontszam>
    </sajatlista>
    <sajatlista f_a_a='a1' f_a_f='f2'>
        <statusz>Megtekintés</statusz>
        <pontszam>7</pontszam>
    </sajatlista>
    <sajatlista f_a_a='a2' f_a_f='f2'>
        <statusz>Befejezett</statusz>
        <pontszam>9</pontszam>
    </sajatlista>
    <sajatlista f_a_a='a2' f_a_f='f3'>
        <statusz>Befejezett</statusz>
        <pontszam>8</pontszam>
    </sajatlista>
    <sajatlista f_a_a='a3' f_a_f='f1'>
        <statusz>Tervezett</statusz>
        <pontszam>8</pontszam>
    </sajatlista>
</myList>
